# yaml-language-server: $schema=https://api.cerbos.dev/latest/cerbos/policy/v1/Policy.schema.json
---
apiVersion: api.cerbos.dev/v1
resourcePolicy:
  version: default
  resource: products
  rules:
    - actions: ["read", "create", "update"]
      effect: EFFECT_ALLOW
      roles:
        - master
        - manager
        - inventory_manager
